### ISSUE TITLE
improve the error handling on the serial port

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-python#211]
If the user does not have sufficient perms on linux, they get this error:

```
./meshtastic --info
Traceback (most recent call last):
  File "meshtastic/__main__.py", line 858, in <module>
  File "meshtastic/__main__.py", line 838, in main
  File "meshtastic/__main__.py", line 638, in common
  File "meshtastic/serial_interface.py", line 45, in __init__
PermissionError: [Errno 13] Permission denied: '/dev/ttyACM0'
[203143] Failed to execute script '__main__' due to unhandled exception!
```

Can this be improved?

**Comment by mkinney** [comment]
Let the user they need to run:
`sudo usermod -a -G dialout username`
Then logout and re-login.

**Comment by mkinney** [comment]
I'm thinking something like this:

```
$ meshtastic --info
Permission Error:
  Need to add yourself to the 'dialout' group by running:
     sudo usermod -a -G dialout myuser
  After running that command, log out and re-login for it to take effect.
Error was:[Errno 13] Permission denied: '/dev/ttyACM0'
```

Note: "myuser" in the above output is the actual user of the person that ran the meshtastic command.

**Comment by mkinney** [comment]
Note: To remove a user from a group:

```
deluser <username> <groupname>
```
