### ISSUE TITLE
Broadcast packet cause Exception("Can not create/find nodenum by the broadcast num")

### ISSUE THREAD

**Issue by tomasbrincil** [meshtastic/Meshtastic-python#99]
When broadcast packet is received function _getOrCreateByNum cause Exception("Can not create/find nodenum by the broadcast num")

```
čen 30 12:17:39 rpi3 python3[1495]: Exception: Can not create/find nodenum by the broadcast num
čen 30 12:17:39 rpi3 python3[1495]: ERROR:root:Error while handling message from radio Can not create/find nodenum by the broadcast num
čen 30 12:17:58 rpi3 python3[1495]: Traceback (most recent call last):
čen 30 12:17:58 rpi3 python3[1495]:   File "/usr/local/lib/python3.7/dist-packages/meshtastic/__init__.py", line 873, in __reader
čen 30 12:17:58 rpi3 python3[1495]:     self._handleFromRadio(self._rxBuf[HEADER_LEN:])
čen 30 12:17:58 rpi3 python3[1495]:   File "/usr/local/lib/python3.7/dist-packages/meshtastic/__init__.py", line 554, in _handleFromRadio
čen 30 12:17:58 rpi3 python3[1495]:     self._handlePacketFromRadio(fromRadio.packet)
čen 30 12:17:58 rpi3 python3[1495]:   File "/usr/local/lib/python3.7/dist-packages/meshtastic/__init__.py", line 680, in _handlePacketFromRadio
čen 30 12:17:58 rpi3 python3[1495]:     handler.onReceive(self, asDict)
čen 30 12:17:58 rpi3 python3[1495]:   File "/usr/local/lib/python3.7/dist-packages/meshtastic/__init__.py", line 1022, in _onTextReceive
čen 30 12:17:58 rpi3 python3[1495]:     _receiveInfoUpdate(iface, asDict)
čen 30 12:17:58 rpi3 python3[1495]:   File "/usr/local/lib/python3.7/dist-packages/meshtastic/__init__.py", line 1046, in _receiveInfoUpdate
čen 30 12:17:58 rpi3 python3[1495]:     iface._getOrCreateByNum(asDict["from"])["lastReceived"] = asDict
čen 30 12:17:58 rpi3 python3[1495]:   File "/usr/local/lib/python3.7/dist-packages/meshtastic/__init__.py", line 595, in _getOrCreateByNum
čen 30 12:17:58 rpi3 python3[1495]:     raise Exception("Can not create/find nodenum by the broadcast num")
čen 30 12:17:58 rpi3 python3[1495]: Exception: Can not create/find nodenum by the broadcast num
čen 30 12:17:58 rpi3 python3[1495]: ERROR:root:Error while handling message from radio Can not create/find nodenum by the broadcast num
```

**Comment by tomasbrincil** [comment]
Ok, so the problem was with nonexisting node id broadcasted to the mesh.
